apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ include "fastapi-helm.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    app: ecommerce
    version: {{.Chart.AppVersion}}
data:
  POSTGRES_DB: c2FtcGxlZGI=
  POSTGRES_USER: bXVrdWxtYW50b3No
  POSTGRES_PASSWORD: bXVrdWwxMjM=
