apiVersion: v1
kind: Secret
metadata:
  name: migration-secret-{{ include "fastapi-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: ecommerce-migration
    version: {{.Chart.AppVersion}}
data:
  DATABASE_USERNAME: bXVrdWxtYW50b3No
  DATABASE_PASSWORD: bXVrdWwxMjM=
  DATABASE_HOST: cG9zdGdyZXMtc2VydmljZQ==
  DATABASE_NAME: c2FtcGxlZGI=