apiVersion: v1
kind: Secret
metadata:
  name: celery-secret-{{ include "fastapi-helm.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    app: ecommerce
    version: {{.Chart.AppVersion}}
data:
  REDIS_HOST: cmVkaXMtc2VydmljZQo=
  REDIS_PORT: NjM3OQo=
  REDIS_DB: MAo=
